name: code-quality

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    services:
      pypi_wayback:
        image: ghcr.io/waleko/pypi-wayback
        ports:
        - 8629:8080

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - run: |
        curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly \
          --profile=minimal -y && rustup show
      if: matrix.os == 'ubuntu-latest'

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -e ".[dev]"

    - name: Run pre-commit on all files
      run: pre-commit run --all-files

env:
  PIP_INDEX_URL: http://localhost:8629/2023-10-31
  UV_INDEX_URL: http://localhost:8629/2023-10-31
